kind: pipeline
name: default
steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: kinnairdclan/docker-openvpn-client
      tags:
        - latest
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_access_token
      context: build/
