kind: pipeline
name: default
steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: kinnairdclan/docker-openvpn-client
      tags:
        - latest
        - v3.1.0
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_access_token
